spring:
  application:
    name: ClassRoomCentre

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/classroomcentre?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        loginUsername: admin
        loginPassword: 123456


  data:
    redis:
      host: localhost
      port: 6379
      database: 8
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
    connection-timeout: 10000
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
      retry:
        enabled: true
        max-attempts: 5
        multiplier: 2
        initial-interval: 1000
        max-interval: 10000
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          initial-interval: 1000ms
          max-interval: 10000ms
          max-attempts: 5
          multiplier: 2
          enabled: true


server:
  port: 8888

redisson:
  singleServerConfig:
    address: redis://localhost:6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  executor-type: batch


