spring:
  application:
    name: ClassRoomCentre

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/classroomcentre?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      database: 8
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8

server:
  port: 8888

redisson:
  singleServerConfig:
    address: redis://localhost:6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
